// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModawantyDAL.Data;

#nullable disable

namespace ModawantyDAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260403143236_addedbio")]
    partial class addedbio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "019a0ee5-cea2-7ffa-9ebe-27d88ee5d111",
                            ConcurrencyStamp = "019a0ee5-csqw-721a-9ege-27d88ee5d111",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "019a0ee5-cea2-7ffa-9ebe-27d9dad81e83",
                            ConcurrencyStamp = "019a0qqw-csqw-721a-9ege-27dhjee5d231",
                            Name = "Member",
                            NormalizedName = "MEMBER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "019a0ee5-cea2-7ffa-abcd-27d88ee5d222",
                            RoleId = "019a0ee5-cea2-7ffa-9ebe-27d88ee5d111"
                        },
                        new
                        {
                            UserId = "019a0ee5-cea2-7ffa-abcd-27d88ee5d222",
                            RoleId = "019a0ee5-cea2-7ffa-9ebe-27d9dad81e83"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ModawantyDAL.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AuthorName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePhoto")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "019a0ee5-cea2-7ffa-abcd-27d88ee5d222",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "066a3373-4233-4400-978a-9c12adf9911d",
                            Email = "Admin25@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "System",
                            LastName = "Admin",
                            LockoutEnabled = true,
                            NormalizedEmail = "admin25@gmail.com",
                            NormalizedUserName = "admin25",
                            PasswordHash = "AQAAAAIAAYagAAAAEOYrXxnIqTyP8L7E3J4G0DQ1lmqWbXxJ8K9Z2lV5pN6M1nW3sY7Z8aB9cD0eF1gH2i==",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "2892fadd-531d-4146-af12-652c98e3a795",
                            TwoFactorEnabled = false,
                            UserName = "Admin25"
                        });
                });

            modelBuilder.Entity("ModawantyDAL.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArticleViews")
                        .HasColumnType("int");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeaturedImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<int?>("ReadTimeInMiniutes")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "د. عمر القاسم",
                            CategoryId = 13,
                            Content = "كيف يمكن استعادة المعنى والحرفية في ظل الثورة الرقمية التي نعيشها اليوم. في عصر التكنولوجيا السريعة والأتمتة، أصبحت القيمة الحقيقية للحرفة والعمل اليدوي والإتقان أكثر أهمية من أي وقت مضى.\r\n\r\nالحرفة ليست مجرد مهارة يدوية، بل هي فلسفة حياة قائمة على الالتزام بالتميز والجودة. في العصور القديمة، كان الحرفيون يكرسون حياتهم لإتقان فنونهم، وكانوا يفخرون بما ينتجونه. كل قطعة كانت انعكاساً لروحهم وقيمهم.\r\n\r\nلكن مع ظهور الثورة الصناعية، تحول التركيز من الجودة إلى الكمية. الإنتاج الضخم والاستهلاك السريع أصبح هو المعيار. ومع الثورة الرقمية، زاد هذا التوجه أكثر فأكثر. كل شيء أصبح سريعاً وسطحياً ومؤقتاً.\r\n\r\nلكن هناك استيقاظ متزايد نحو قيمة الحرفة الحقيقية. الناس بدأوا يدركون أن السعادة الحقيقية لا تأتي من امتلاك أشياء كثيرة، بل من امتلاك أشياء ذات قيمة حقيقية. الحرفة اليدوية، الاهتمام بالتفاصيل، والإتقان أصبحوا يحظون بتقدير متجدد.\r\n\r\nالحرفيون المعاصرون يجمعون بين المهارات القديمة والأدوات الحديثة. إنهم يستخدمون التكنولوجيا ليس لاستبدال الحرفة، بل لتحسينها وتطويرها. هذا التوازن بين القديم والحديث هو ما يعطي المعنى الحقيقي للعمل.\r\n\r\nاستعادة فلسفة الحرفة تتطلب تغييراً في منظورنا. نحتاج إلى تقدير الوقت والجهد المستثمر في أي عمل. نحتاج إلى فهم أن الجودة تتطلب صبراً وإصراراً. نحتاج إلى استعادة الفخر بما ننتجه، سواء كان مادياً أو فكرياً.\r\n\r\nفي العصر الرقمي، يمكن أن تكون الحرفة موجودة في كل مكان: في الكتابة، في البرمجة، في التصميم، في التعليم. أينما كان هناك التزام بالتميز والجودة، هناك توجد الحرفة. هذه هي الطريقة لاستعادة المعنى في عصرنا الرقمي.",
                            CreatedAt = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FeaturedImageUrl = "https://lh3.googleusercontent.com/aida-public/AB6AXuACPRZ9fApQxZLggAWFDuWdIJgqrOMNi9sX5KjHSryiEVOYJ3hUkxRNMK4Aa9puI9is71mYzAWUKRhGZaEkYfXJ6ggSMIAD5u1van0tTGGdnowpa1ZQtlaZ7Ci7czmhyX_Mg2lxYWHpkvuCaSQYkapc_LlxNgdm303JCq_TasKX3CmY2jSuN3NoiW-huyZXFBpTXCfP6gDmmYDGH_UeAHG3Huy_B8zRrN5pSUedJv-XZf2YqpLxaqGMeKY8MqJv4FewQMZRoBJWWWPA",
                            IsDeleted = false,
                            IsPublished = true,
                            Title = "فلسفة الحرفة في العصر الرقمي: استعادة المعنى"
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "د. يوسف المنصور",
                            CategoryId = 5,
                            Content = "رحلة عبر المخطوطات والوثائق التاريخية لفهم كيف تم تدوين تاريخ الأندلس. الأندلس كانت حضارة متقدمة وغنية بالثقافات المتعددة، لكن كيف تم تدوين تاريخها؟ هل كانت الروايات التاريخية موثوقة أم أن كل مؤرخ أضاف لمسته الخاصة؟\r\n\r\nالمخطوطات الأندلسية تخبرنا الكثير عن الحياة في تلك الفترة. ابن حزم، الطبري، المقري وغيرهم من المؤرخين الأندلسيين تركوا لنا سجلات مفصلة عن الأحداث والحياة اليومية. لكن هذه الروايات تختلف أحياناً، مما يثير أسئلة حول الحقيقة والتفسير.\r\n\r\nالتاريخ ليس حقيقة مطلقة، بل هو تفسير من قبل شهود أو مؤرخين. كل راوٍ يختار التفاصيل التي يراها مهمة، ويترك جانباً ما يعتبره ثانوياً. هذا يعني أن تاريخ الأندلس الذي نعرفه اليوم هو انعكاس لاختيارات المؤرخين الأندلسيين وليس الحقيقة المطلقة.\r\n\r\nالخيال أيضاً لعب دوراً في تدوين التاريخ. الشعر والأدب كانا طرقاً للتعبير عن الأحداث التاريخية. القصائد والقصص الأدبية ساهمت في نقل الروح الحقيقية للعصر، حتى لو لم تكن دقيقة من الناحية الحرفية.\r\n\r\nعندما نقرأ تاريخ الأندلس اليوم، نحن نقرأ خليطاً من الحقيقة والخيال، من السجلات الموثوقة والرويات الملونة. هذا المزيج هو الذي يعطي لتاريخ الأندلس عمقه وجماله. نحن لا نتعرف على حقائق جافة، بل على قصة حية وممتعة.\r\n\r\nفهم هذا الفرق مهم لمن يدرس التاريخ. يجب أن نقرأ المصادر الأصلية بعين ناقدة، وأن نحاول فهم سياق كل رواية. يجب أن نقدر الجهد الذي بذله المؤرخون القدماء في حفظ ذاكرة حضارتهم.\r\n\r\nالأندلس تبقى واحدة من أعظم الحضارات في التاريخ، وتدوينها ظل أحد أعظم الإنجازات في تاريخ الكتابة التاريخية. مزجها بين الدقة والجمال، بين الحقيقة والخيال، أعطاها نسيجاً فريداً من نوعه.",
                            CreatedAt = new DateTime(2024, 5, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            FeaturedImageUrl = "https://lh3.googleusercontent.com/aida-public/AB6AXuDvTOcb-4WoMNK3FNHOWAcTbvAFvAD0hiv1psKJfVJwybTcPE53lT5uI4ykosZhyRTIspUWKuhLGxv5Z9Cs6mps1oc44soP13Ya5kISixiw8_iuWR74l-ZiTu5vTztHb4eiQEIlO7ub5EY4AdtEcsFQwSEnwkEjld2rTDx1QuKRBZpqRUoyNc3ziDBSh9759mJ_3sF0LQYe0tiPbQp9XIs4czw-w-bS0Wir1NOEfQZ4J__rQnpI-WbTNij60X-9ZG3tM53Krumer9Sk",
                            IsDeleted = false,
                            IsPublished = true,
                            Title = "بين الحقيقة والخيال: تدوين التاريخ في الأندلس"
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "أ. ليلى حسن",
                            CategoryId = 13,
                            Content = "استكشاف تاريخ المجالس الأدبية في العواصم العربية ودورها في إثراء الثقافة. المجالس الأدبية كانت مراكز إشعاع ثقافي في عواصمنا العربية. في هذه المجالس، كان يجتمع الأدباء والشعراء والفلاسفة لمناقشة الأفكار وتبادل الآراء.\r\n\r\nمجالس بغداد في العصر العباسي كانت أسطورية. هنا التقى الكندي والفارابي والجاحظ وغيرهم من الفلاسفة والكتاب العظماء. كانوا يناقشون الفلسفة واللغة والأدب والعلوم. هذه المجالس أنتجت أعظم الأعمال الفكرية للحضارة الإسلامية.\r\n\r\nفي دمشق والقاهرة وقرطبة، كانت هناك مجالس أدبية متشابهة. في الأندلس، كانت مجالس الأمراء والعلماء مراكز للحوار الثقافي. المعتمد بن عباد، على سبيل المثال، كان يجمع حوله الشعراء والعلماء في مجالسه الشهيرة.\r\n\r\nهذه المجالس لم تكن مجرد اجتماعات اجتماعية. كانت مراكس للبحث والتطور الفكري. هنا ولدت الأفكار الجديدة، وتم نقد الأفكار القديمة. هنا تم تشكيل الذوق الأدبي والفكري لأجيال.\r\n\r\nالحوار في هذه المجالس كان حراً وتفاعلياً. كان الاختلاف في الرأي مقبولاً بل مرحباً به. هذه الحرية الفكرية أدت إلى إثراء الثقافة والأدب. من هنا خرجت أعظم الروائع الأدبية والفكرية.\r\n\r\nاليوم، مجالس الأدب أصبحت أقل شيوعاً. الإنترنت والوسائط الرقمية غيرت طريقة حوارنا. لكن هناك محاولات لاستعادة روح المجالس الأدبية التقليدية. في دول عربية مختلفة، هناك مجالس أدبية تحاول أن تحافظ على التقليد القديم.\r\n\r\nذاكرة هذه المجالس ما زالت حية في تراثنا الأدبي. الحوارات التي دارت فيها، الأفكار التي ولدت فيها، كل هذا بقي محفوظاً في المخطوطات والمؤلفات. قراءة هذه المخطوطات تعيدنا إلى عالم مختلف من الحوار الثقافي الغني.",
                            CreatedAt = new DateTime(2024, 5, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            FeaturedImageUrl = "https://lh3.googleusercontent.com/aida-public/AB6AXuDnKRzkjPE9Aa-O8S8G4O93mMJ6EWDq7GGhlK16BDgkglA9Jf9ohWLiD27FiI15QakRI2kKzxX-1kRd6M9_jTQ0wo1RtH6whXEMJuCkne87RfpMDeebo63iIL66vaZaxXY3o3oXw6K5nd--ZEyD3H95zaQXU_O1ib9l5Y7vJGbi5nv5k6zkdWETfluxuPBvhLIyZ-KJJsFLF17hfCt-VgBGqD9GWO6Lss3rfVdyLFbWdpahbR-ifnaa1WrzqXAHbsOuJeGlrWGShubr",
                            IsDeleted = false,
                            IsPublished = true,
                            Title = "مجالس الأدب في العواصم العربية: ذاكرة الحوار"
                        },
                        new
                        {
                            Id = 4,
                            AuthorName = "أ. سارة الراشد",
                            CategoryId = 1,
                            Content = "نقاش معمّق حول تأثير تقنيات الذكاء الاصطناعي على الهوية الثقافية العربية. الذكاء الاصطناعي يغير طريقة تفكيرنا وعملنا وتعاملنا مع العالم. لكن ماذا عن تأثيره على هويتنا الثقافية؟\r\n\r\nالتكنولوجيا لطالما كانت أداة للتبديل الثقافي. الطباعة غيرت طريقة نشر المعرفة. الإذاعة والتلفاز غيرا طريقة استقبالنا للمعلومات والثقافة. الإنترنت فتح آفاقاً جديدة للتبادل الثقافي. والآن، الذكاء الاصطناعي يأتي بتأثيرات جديدة ومختلفة.\r\n\r\nمن جهة، الذكاء الاصطناعي يمكنه أن يساهم في الحفاظ على الثقافة العربية. يمكن استخدامه لحفظ النصوص القديمة، لترجمة الأعمال الأدبية، لتطوير محررات نصية تدعم اللغة العربية بشكل أفضل. التطبيقات التعليمية القائمة على الذكاء الاصطناعي يمكنها أن تعلم الأجيال الجديدة عن تراثنا.\r\n\r\nلكن من جهة أخرى، هناك تهديدات حقيقية. الخوارزميات التي تدفع بنا نحو محتوى معين قد تحد من تنوعنا الثقافي. إذا كانت معظم الذكاء الاصطناعي مبني على البيانات الغربية، فقد ينعكس هذا في المحتوى الذي يتم توليده. الثقافة العربية قد تصبح هامشية في عالم يحكمه الذكاء الاصطناعي.\r\n\r\nهناك أيضاً مسألة الملكية الثقافية. عندما يتم استخدام الأعمال الأدبية العربية القديمة لتدريب نماذج الذكاء الاصطناعي، من يستفيد من هذا؟ هل حقوق المؤلفين والثقافة محمية؟\r\n\r\nالحقيقة أن الذكاء الاصطناعي بحد ذاته لا يهدد ولا ينقذ الهوية الثقافية. كل يتعلق بكيفية استخدامنا له. إذا استخدمناه بحكمة، يمكن أن يكون أداة قوية لنشر وحفظ ثقافتنا. لكن إذا تركنا له الحبل على الغارب، قد نجد أنفسنا نسير بدون اتجاه.\r\n\r\nنحتاج إلى مناقشات جادة حول كيفية استخدام الذكاء الاصطناعي بطريقة تحافظ على هويتنا الثقافية. نحتاج إلى تطوير نماذج ذكاء اصطناعي عربية مبنية على قيمنا وثقافتنا. نحتاج إلى الحفاظ على السيطرة على أدواتنا، بدلاً من السماح لها بالسيطرة علينا.",
                            CreatedAt = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FeaturedImageUrl = "https://lh3.googleusercontent.com/aida-public/AB6AXuBhLMRuyipwroCSKOsyhP0lA5dVBI4Dq9GPVGay4QTwlSpTCSq8_KbmReL0b0k-lskINCCJ_WVXMTkIwA-wwZDQDyMyx03lX4M3m2awmNqOiiIjIT0eaceEIeInzxSq5QCJsIdldPJyqyJX-yL4Ug82heunZRrc7oIEorvN6ChFbjUcCKtpggpNAYgZFQe51T_nDYWKYwzbxRW7cYyTAymM6YRuwu5eQXmDNVKgt4TfA_JX0VnbKm94gn1eg_EqWRI3fLnH6cbz_nMu",
                            IsDeleted = false,
                            IsPublished = true,
                            Title = "الذكاء الاصطناعي: هل يهدد الهوية الثقافية؟"
                        },
                        new
                        {
                            Id = 5,
                            AuthorName = "د. عمر القاسم",
                            CategoryId = 13,
                            Content = "نظرة عميقة في الجذور الفكرية وكيف ساهمت في تشكيل الوعي المعاصر، مستكشفين الفراغ والضوء كعناصر روحية قبل أن تكون مادية. العمارة الإسلامية ليست مجرد عن بناء المساجد والقصور، بل هي تعبير عن رؤية كاملة للعالم.\r\n\r\nالفراغ في العمارة الإسلامية لم يكن فراغاً فارغاً. كان فراغاً مقصوداً، معبراً عن اللانهاية والخلود. الصحن الكبير في المسجد، المساحات المفتوحة بين الأعمدة، كل هذا كان جزءاً من فلسفة معينة. كانت العمارة الإسلامية تعلمنا أن الفراغ يمكن أن يكون له معنى، وأن الصمت يمكن أن يكون له صوت.\r\n\r\nالضوء أيضاً كان عنصراً روحياً في العمارة الإسلامية. الضوء الذي يخترق النوافذ الصغيرة والكبيرة، الظل الذي ينشأ من الأقواس والقباب، كل هذا كان جزءاً من تجربة روحية. المعمار الإسلامي كان يفهم أن الضوء والظل يمكنهما أن يؤثرا على الروح والعقل.\r\n\r\nالزخرفة الهندسية في العمارة الإسلامية لم تكن مجرد زينة. كانت محاولة لتمثيل الانسجام والنظام الكوني. الأنماط المتكررة، الأشكال الهندسية المعقدة، كل هذا كان انعكاساً لفهم عميق للرياضيات والفلسفة.\r\n\r\nالمسجد الإسلامي كان مساحة للتأمل والروحانية. ليس فقط بسبب الدين، بل أيضاً بسبب الطريقة التي تم تصميمها. المعماري الإسلامي كان يريد أن ينقل الإنسان من عالم الدنيا المادي إلى عالم روحاني أعلى. كل عنصر معماري كان جزءاً من هذه الرحلة.\r\n\r\nاليوم، يمكننا أن نتعلم الكثير من هذه الفلسفة المعمارية. في عالم يصرخ من الضوضاء والفوضى، يمكننا أن نجد السلام والهدوء في الفراغات المصممة بحكمة. في عالم يحتفي بالحشو والامتلاء، يمكننا أن نجد الجمال في البساطة والخطوط النظيفة.\r\n\r\nعمارة الروح الإسلامية تعلمنا أن العمارة ليست مجرد شكل وأسمنت، بل هي تجربة كاملة، تأثير على الروح والعقل والجسد. هذا الفهم العميق هو ما يميز العمارة الإسلامية ويجعلها خالدة.",
                            CreatedAt = new DateTime(2024, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            FeaturedImageUrl = "https://lh3.googleusercontent.com/aida-public/AB6AXuAGaMizZifHeSWvvhp1FkJga8F5up4hBKUMUH-VMa1wk6VJ2-EjtLe984hkBoyUTPDlBJmFmIiKDDnTDZJy9g1H-AXNfVHaxnnK8DakMOoGV_ndmBUJAwEXYE-Y9d3mg2yNR1bi7EuJBKI640IIf4MhHyZYquCpEhMPOQUsnnb0pyypJUMi9JlX80vL1wBnbOCYQduWkgFmiZIJUjMDuOImss_626cy6ug3PVaMqGyqNQawEdvbcOSlhYASY0fjDsNGn014eWTQrqG5",
                            IsDeleted = false,
                            IsPublished = true,
                            Title = "عمارة الروح: تأملات في الفلسفة المعمارية الإسلامية"
                        },
                        new
                        {
                            Id = 6,
                            AuthorName = "د. أحمد السيد",
                            CategoryId = 13,
                            Content = "استكشاف مفهوم الزمن في التراث الصوفي والتفسيرات المختلفة للزمن الروحي. الصوفيون القدماء لم ينظروا إلى الزمن كما نظرنا إليه نحن في العصر الحديث. الزمن لم يكن مجرد ساعات ودقائق، بل كان تجربة وحالة روحية.\r\n\r\nفي الفكر الصوفي، الزمن لديه أبعاد متعددة. هناك الزمن الخارجي، زمن الساعة والتاريخ. وهناك الزمن الداخلي، زمن الروح والقلب. الصوفي كان يسعى للتجاوز من الزمن الخارجي إلى الزمن الداخلي، من المادي إلى الروحي.\r\n\r\nالصوفيون تحدثوا عن حالات يختفي فيها الزمن تماماً. في لحظات من التأمل العميق أو الانجذاب الروحي، يشعر الصوفي أنه خارج الزمن. اللحظة تصبح أبدية، والأبدية تصبح حاضرة الآن.",
                            CreatedAt = new DateTime(2024, 5, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            FeaturedImageUrl = "https://via.placeholder.com/400x300?text=Sufi+Thought",
                            IsDeleted = false,
                            IsPublished = true,
                            Title = "مفهوم الزمن في الفكر الصوفي القديم"
                        },
                        new
                        {
                            Id = 7,
                            AuthorName = "د. سارة محمود",
                            CategoryId = 13,
                            Content = "دراسة حول كيف تجلت الحداثة في الشعر العربي المعاصر وتأثيرها على الشعراء. الشعر العربي المعاصر شهد ثورة حقيقية عندما بدأ الشعراء يتحررون من القيود التقليدية. الشعر الحر والتفعيلة أتاحا للشعراء مساحات أكبر للتجريب والابتكار.\r\n\r\nنزار قباني، أدونيس، سميح القاسم وغيرهم من الشعراء المعاصرين احدثوا ثورة في الشعر العربي. جلبوا لغة جديدة، موضوعات جديدة، أساليب جديدة. الحداثة لم تكن مجرد شكل جديد، بل فلسفة جديدة لفهم الشعر والكتابة.\r\n\r\nالشعر المعاصر أصبح أكثر انفتاحاً على التجارب الشخصية والسياسية والاجتماعية. لا يعود الشاعر ملزماً بمواضيع معينة أو أشكال محددة. الحرية التي جلبتها الحداثة سمحت للشعراء أن يصرخوا من قلوبهم.",
                            CreatedAt = new DateTime(2024, 5, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            FeaturedImageUrl = "https://via.placeholder.com/400x300?text=Modern+Poetry",
                            IsDeleted = false,
                            IsPublished = true,
                            Title = "تجليات الحداثة في الشعر العربي المعاصر"
                        },
                        new
                        {
                            Id = 8,
                            AuthorName = "أ. محمد علي",
                            CategoryId = 14,
                            Content = "دراسة حول كيف تؤثر البيئة العمرانية على الوعي والصحة النفسية للإنسان. المدينة ليست مجرد مجموعة من المباني والطرق. المدينة لها روح، وهذه الروح تؤثر على الناس الذين يعيشون فيها.\r\n\r\nالتصميم العمراني يؤثر على الحالة النفسية للإنسان. المدن الضيقة والمزدحمة تخلق ضغوطاً نفسية. المدن الواسعة والمفتوحة تجلب الاستقرار والسلام. الألوان، الأضواء، الأصوات، كل هذا يؤثر على وعينا بطرق قد لا ندركها.",
                            CreatedAt = new DateTime(2024, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            FeaturedImageUrl = "https://via.placeholder.com/400x300?text=Urban+Psychology",
                            IsDeleted = false,
                            IsPublished = true,
                            Title = "سيكولوجية المدن: كيف تؤثر البيئة على الوعي"
                        },
                        new
                        {
                            Id = 9,
                            AuthorName = "د. فاطمة النعمان",
                            CategoryId = 5,
                            Content = "تحليل شامل لتحديات ومستقبل اللغة العربية في عصر العولمة والتكنولوجيا. اللغة العربية تواجه تحديات حقيقية في العصر الحديث. الإنجليزية أصبحت لغة العلم والتكنولوجيا والعمل. الشباب يستخدمون لغة مختلطة، مزيج من العربية والإنجليزية والعامية.\r\n\r\nلكن اللغة العربية لم تمت. هناك محاولات جادة لتطويرها وجعلها تواكب العصر. المعاجم الإلكترونية، التطبيقات التعليمية، المحتوى الرقمي العربي، كل هذا يساهم في الحفاظ على اللغة وتطويرها.\r\n\r\nمستقبل اللغة العربية يعتمد على اهتمام الأجيال الجديدة بها. إذا استطعنا أن نجعل اللغة العربية جذابة وملائمة للعصر، يمكننا أن نضمن بقاؤها وازدهارها.",
                            CreatedAt = new DateTime(2024, 5, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            FeaturedImageUrl = "https://via.placeholder.com/400x300?text=Arabic+Language",
                            IsDeleted = false,
                            IsPublished = true,
                            Title = "مستقبل اللغة العربية في ظل العولمة"
                        },
                        new
                        {
                            Id = 10,
                            AuthorName = "د. محمود الأحمد",
                            CategoryId = 13,
                            Content = "رحلة الكتابة الإبداعية من العصر الكلاسيكي إلى العصر الرقمي. الكتابة الإبداعية تطورت بشكل كبير مع تطور التكنولوجيا. من الورقة والحبر إلى الحاسوب والإنترنت، الكتابة أصبحت أكثر سهولة ولكن أيضاً أكثر تحدياً.\r\n\r\nالكاتب المعاصر يواجه فرصاً جديدة وتحديات جديدة. من جهة، يمكنه أن ينشر أعماله مباشرة للعالم. من جهة أخرى، يجب أن يتنافس مع ملايين الكتاب الآخرين. الجودة أصبحت أكثر أهمية من أي وقت مضى.\r\n\r\nالكتابة الإبداعية اليوم لا تقتصر على الرواية والقصة والشعر. هناك أشكال جديدة مثل الكتابة للإنترنت والتدوين والكتابة للعاب. كل هذه الأشكال تتطلب مهارات جديدة ومنهجيات جديدة.",
                            CreatedAt = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            FeaturedImageUrl = "https://via.placeholder.com/400x300?text=Creative+Writing",
                            IsDeleted = false,
                            IsPublished = true,
                            Title = "الكتابة الإبداعية: من الورقة إلى الشاشة"
                        });
                });

            modelBuilder.Entity("ModawantyDAL.Models.ArticleTag", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("ArticleId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ArticleTags");

                    b.HasData(
                        new
                        {
                            ArticleId = 1,
                            TagId = 14
                        },
                        new
                        {
                            ArticleId = 1,
                            TagId = 13
                        },
                        new
                        {
                            ArticleId = 1,
                            TagId = 15
                        },
                        new
                        {
                            ArticleId = 2,
                            TagId = 14
                        },
                        new
                        {
                            ArticleId = 2,
                            TagId = 13
                        },
                        new
                        {
                            ArticleId = 2,
                            TagId = 15
                        },
                        new
                        {
                            ArticleId = 3,
                            TagId = 14
                        },
                        new
                        {
                            ArticleId = 3,
                            TagId = 15
                        },
                        new
                        {
                            ArticleId = 3,
                            TagId = 8
                        },
                        new
                        {
                            ArticleId = 4,
                            TagId = 13
                        },
                        new
                        {
                            ArticleId = 4,
                            TagId = 14
                        },
                        new
                        {
                            ArticleId = 4,
                            TagId = 10
                        },
                        new
                        {
                            ArticleId = 5,
                            TagId = 14
                        },
                        new
                        {
                            ArticleId = 5,
                            TagId = 13
                        },
                        new
                        {
                            ArticleId = 5,
                            TagId = 15
                        },
                        new
                        {
                            ArticleId = 6,
                            TagId = 14
                        },
                        new
                        {
                            ArticleId = 6,
                            TagId = 15
                        },
                        new
                        {
                            ArticleId = 6,
                            TagId = 8
                        },
                        new
                        {
                            ArticleId = 7,
                            TagId = 14
                        },
                        new
                        {
                            ArticleId = 7,
                            TagId = 13
                        },
                        new
                        {
                            ArticleId = 7,
                            TagId = 15
                        },
                        new
                        {
                            ArticleId = 8,
                            TagId = 13
                        },
                        new
                        {
                            ArticleId = 8,
                            TagId = 14
                        },
                        new
                        {
                            ArticleId = 8,
                            TagId = 10
                        },
                        new
                        {
                            ArticleId = 9,
                            TagId = 14
                        },
                        new
                        {
                            ArticleId = 9,
                            TagId = 15
                        },
                        new
                        {
                            ArticleId = 9,
                            TagId = 8
                        },
                        new
                        {
                            ArticleId = 10,
                            TagId = 13
                        },
                        new
                        {
                            ArticleId = 10,
                            TagId = 14
                        },
                        new
                        {
                            ArticleId = 10,
                            TagId = 15
                        });
                });

            modelBuilder.Entity("ModawantyDAL.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasComment("Book description/synopsis");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Author name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasComment("UTC timestamp when book was added to database");

                    b.Property<string>("DownloadLink")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Cloudinary HTTPS URL for downloading the PDF file");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Soft delete flag - true means book is deleted but data preserved in database");

                    b.Property<int>("PageCount")
                        .HasColumnType("int")
                        .HasComment("Total number of pages in the book");

                    b.Property<string>("Poster")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Local path to book poster image (stored in wwwroot/books/)");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date")
                        .HasComment("Original release/publication date");

                    b.Property<string>("SaveLocation")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasComment("Cloudinary public ID used to delete the PDF from cloud storage");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Book title - must be unique");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "Even bad code can function. But if code isn't clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are spent fixing fragile and broken code. But it doesn't have to be that way.",
                            Author = "Robert C. Martin",
                            CreatedAt = new DateTime(2024, 1, 15, 10, 30, 0, 0, DateTimeKind.Utc),
                            DownloadLink = "uploading",
                            IsDeleted = false,
                            PageCount = 464,
                            Poster = "https://covers.openlibrary.org/b/isbn/9780132350884-M.jpg",
                            ReleaseDate = new DateOnly(2008, 8, 1),
                            SaveLocation = "pending_upload",
                            Title = "Clean Code: A Handbook of Agile Software Craftsmanship"
                        },
                        new
                        {
                            Id = 2,
                            About = "The Pragmatic Programmer is about taking charge of your career. Be pragmatic. Make choices based on analysis and commonsense. Look at the state of the art, but also consider your own needs.",
                            Author = "David Thomas, Andrew Hunt",
                            CreatedAt = new DateTime(2024, 1, 18, 14, 45, 0, 0, DateTimeKind.Utc),
                            DownloadLink = "uploading",
                            IsDeleted = false,
                            PageCount = 352,
                            Poster = "https://covers.openlibrary.org/b/isbn/9780135957059-M.jpg",
                            ReleaseDate = new DateOnly(2019, 10, 1),
                            SaveLocation = "pending_upload",
                            Title = "The Pragmatic Programmer: Your Journey to Mastery"
                        },
                        new
                        {
                            Id = 3,
                            About = "Capturing a wealth of experience about the design of object-oriented software, four top-notch designers present a catalog of simple and elegant solutions to commonly occurring design problems.",
                            Author = "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
                            CreatedAt = new DateTime(2024, 1, 20, 9, 15, 0, 0, DateTimeKind.Utc),
                            DownloadLink = "uploading",
                            IsDeleted = false,
                            PageCount = 395,
                            Poster = "https://covers.openlibrary.org/b/isbn/9780201633610-M.jpg",
                            ReleaseDate = new DateOnly(1994, 10, 31),
                            SaveLocation = "pending_upload",
                            Title = "Design Patterns: Elements of Reusable Object-Oriented Software"
                        },
                        new
                        {
                            Id = 4,
                            About = "Some books on algorithms are written to teach students. Some are written as reference material. Introduction to Algorithms was conceived as a comprehensive textbook covering the full scope of computer algorithms.",
                            Author = "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein",
                            CreatedAt = new DateTime(2024, 1, 22, 16, 20, 0, 0, DateTimeKind.Utc),
                            DownloadLink = "uploading",
                            IsDeleted = false,
                            PageCount = 1312,
                            Poster = "https://covers.openlibrary.org/b/isbn/9780262033848-M.jpg",
                            ReleaseDate = new DateOnly(2009, 7, 31),
                            SaveLocation = "pending_upload",
                            Title = "Introduction to Algorithms"
                        },
                        new
                        {
                            Id = 5,
                            About = "The You Don't Know JS Yet book series is aimed at everyone seeking to learn and deepen their understanding of the JavaScript programming language. Everyone starts somewhere.",
                            Author = "Kyle Simpson",
                            CreatedAt = new DateTime(2024, 1, 25, 11, 50, 0, 0, DateTimeKind.Utc),
                            DownloadLink = "uploading",
                            IsDeleted = false,
                            PageCount = 432,
                            Poster = "https://covers.openlibrary.org/b/isbn/9781492091523-M.jpg",
                            ReleaseDate = new DateOnly(2020, 1, 28),
                            SaveLocation = "pending_upload",
                            Title = "You Don't Know JS Yet"
                        },
                        new
                        {
                            Id = 6,
                            About = "These seminal works are an essential resource in the personal library of any serious programmer. Countless readers have spoken about the profound personal impact of Knuth's work.",
                            Author = "Donald E. Knuth",
                            CreatedAt = new DateTime(2024, 1, 28, 13, 30, 0, 0, DateTimeKind.Utc),
                            DownloadLink = "uploading",
                            IsDeleted = false,
                            PageCount = 883,
                            Poster = "https://covers.openlibrary.org/b/isbn/9780201896830-M.jpg",
                            ReleaseDate = new DateOnly(1997, 6, 15),
                            SaveLocation = "pending_upload",
                            Title = "The Art of Computer Programming"
                        });
                });

            modelBuilder.Entity("ModawantyDAL.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAvailable = true,
                            Name = "تكنولوجيا"
                        },
                        new
                        {
                            Id = 2,
                            IsAvailable = true,
                            Name = "العلوم"
                        },
                        new
                        {
                            Id = 3,
                            IsAvailable = true,
                            Name = "الأعمال"
                        },
                        new
                        {
                            Id = 4,
                            IsAvailable = true,
                            Name = "الصحة"
                        },
                        new
                        {
                            Id = 5,
                            IsAvailable = true,
                            Name = "التعليم"
                        },
                        new
                        {
                            Id = 6,
                            IsAvailable = true,
                            Name = "الرياضة"
                        },
                        new
                        {
                            Id = 7,
                            IsAvailable = true,
                            Name = "الترفيه"
                        },
                        new
                        {
                            Id = 8,
                            IsAvailable = true,
                            Name = "السفر"
                        },
                        new
                        {
                            Id = 9,
                            IsAvailable = true,
                            Name = "الطعام"
                        },
                        new
                        {
                            Id = 10,
                            IsAvailable = true,
                            Name = "الموضة"
                        },
                        new
                        {
                            Id = 11,
                            IsAvailable = true,
                            Name = "نمط الحياة"
                        },
                        new
                        {
                            Id = 12,
                            IsAvailable = true,
                            Name = "السياسة"
                        },
                        new
                        {
                            Id = 13,
                            IsAvailable = true,
                            Name = "الثقافة"
                        },
                        new
                        {
                            Id = 14,
                            IsAvailable = true,
                            Name = "البيئة"
                        },
                        new
                        {
                            Id = 15,
                            IsAvailable = true,
                            Name = "الابتكار"
                        });
                });

            modelBuilder.Entity("ModawantyDAL.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("ModawantyDAL.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAvailable = true,
                            Name = "برمجة"
                        },
                        new
                        {
                            Id = 2,
                            IsAvailable = true,
                            Name = "تصميم"
                        },
                        new
                        {
                            Id = 3,
                            IsAvailable = true,
                            Name = "تسويق"
                        },
                        new
                        {
                            Id = 4,
                            IsAvailable = true,
                            Name = "إدارة"
                        },
                        new
                        {
                            Id = 5,
                            IsAvailable = true,
                            Name = "استثمار"
                        },
                        new
                        {
                            Id = 6,
                            IsAvailable = true,
                            Name = "ريادة الأعمال"
                        },
                        new
                        {
                            Id = 7,
                            IsAvailable = true,
                            Name = "تدريب"
                        },
                        new
                        {
                            Id = 8,
                            IsAvailable = true,
                            Name = "مهارات"
                        },
                        new
                        {
                            Id = 9,
                            IsAvailable = true,
                            Name = "قيادة"
                        },
                        new
                        {
                            Id = 10,
                            IsAvailable = true,
                            Name = "ابتكار"
                        },
                        new
                        {
                            Id = 11,
                            IsAvailable = true,
                            Name = "استراتيجية"
                        },
                        new
                        {
                            Id = 12,
                            IsAvailable = true,
                            Name = "تطوير"
                        },
                        new
                        {
                            Id = 13,
                            IsAvailable = true,
                            Name = "تحليل"
                        },
                        new
                        {
                            Id = 14,
                            IsAvailable = true,
                            Name = "بحث"
                        },
                        new
                        {
                            Id = 15,
                            IsAvailable = true,
                            Name = "توعية"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ModawantyDAL.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ModawantyDAL.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModawantyDAL.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ModawantyDAL.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModawantyDAL.Models.Article", b =>
                {
                    b.HasOne("ModawantyDAL.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ModawantyDAL.Models.ArticleTag", b =>
                {
                    b.HasOne("ModawantyDAL.Models.Article", "Article")
                        .WithMany("ArticleTags")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModawantyDAL.Models.Tag", "Tag")
                        .WithMany("ArticleTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ModawantyDAL.Models.Comment", b =>
                {
                    b.HasOne("ModawantyDAL.Models.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModawantyDAL.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ModawantyDAL.Models.Article", b =>
                {
                    b.Navigation("ArticleTags");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("ModawantyDAL.Models.Tag", b =>
                {
                    b.Navigation("ArticleTags");
                });
#pragma warning restore 612, 618
        }
    }
}
